@php($navigation = config('portals.supplier_navigation'))
<x-portal-layout title="My Products" portal-name="Supplier Portal" :navigation="$navigation" search-placeholder="Search my products...">
    <x-slot name="header"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-2xl font-extrabold text-[#071d4f]">My products and stock</h1><p class="mt-1 text-sm text-slate-500">Supplier-owned stock approved for direct fulfilment.</p></div><a href="{{ route('supplier.offers.create') }}" class="inline-flex min-h-10 items-center gap-2 rounded-md bg-emerald-700 px-4 text-sm font-bold text-white"><x-ui.icon name="plus" size="size-4" />Add product or stock</a></div></x-slot>
    <div class="px-4 py-6 sm:px-6 lg:px-8"><div class="mx-auto max-w-[1500px] space-y-5">
        @if (session('status'))<div class="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
        <section class="overflow-hidden rounded-md border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Product</th><th class="px-5 py-3">Supplier price</th><th class="px-5 py-3">Customer price</th><th class="px-5 py-3">Available</th><th class="px-5 py-3">Sold</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Restock</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse ($offers as $offer)<tr><td class="px-5 py-4"><p class="font-bold text-[#071d4f]">{{ $offer->product?->name ?? $offer->submitted_name }}</p><p class="text-xs text-slate-500">{{ $offer->product?->sku ?? 'New product proposal' }}</p></td><td class="px-5 py-4 font-semibold">UGX {{ number_format($offer->supplier_price) }}</td><td class="px-5 py-4">{{ $offer->customer_price ? 'UGX '.number_format($offer->customer_price) : '-' }}</td><td class="px-5 py-4 font-bold">{{ number_format($offer->quantity_available) }}</td><td class="px-5 py-4">{{ number_format($offer->quantity_sold) }}</td><td class="px-5 py-4"><span class="rounded px-2 py-1 text-xs font-bold {{ $offer->status === 'approved' ? 'bg-emerald-50 text-emerald-700' : ($offer->status === 'rejected' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700') }}">{{ ucfirst($offer->status) }}</span>@if($offer->review_notes)<p class="mt-1 max-w-52 text-xs text-slate-500">{{ $offer->review_notes }}</p>@endif</td><td class="px-5 py-4">@if($offer->product_id && $offer->status === 'approved')<form method="POST" action="{{ route('supplier.offers.restock', $offer) }}" class="flex gap-2">@csrf<input name="quantity" type="number" min="1" required class="h-9 w-20 rounded-md border-slate-300 text-sm" placeholder="Qty"><button class="rounded-md border border-emerald-300 px-3 text-xs font-bold text-emerald-700">Submit</button></form>@else<span class="text-xs text-slate-400">After approval</span>@endif</td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">No supplier products submitted yet.</td></tr>@endforelse
        </tbody></table></div></section>{{ $offers->links() }}
    </div></div>
</x-portal-layout>
